openapi: "3.0.3"

info:
  title: "Shop Review API"
  version: "1.0.0"

tags: []

paths:
  "/shops/{shopId}/reviews":
    get:
      summary: "Get shop review"
      description: "Get specified shop's reviews"
      deprecated: false
      parameters:
        - name: "shopId"
          in: "path"
          required: true
          schema: { type: string, example: "1" }
      responses:
        "200":
          description: "Succes operation"
