openapi: "3.0.3"

info:
  title: "Shop Review API"
  version: "1.0.0"

servers:
  - url: "http://localhost:{port}"
    description: "Local Development"
    variables:
      port:
        enum: ["3000", "8000"]
        default: "3000"

  - url: "https://staging.codes"
    description: "Staging"

  - url: "https://shop-review.com"
    description: "Production"

paths: {}
