openapi: "3.0.3"

info:
  title: "Shop Review API"
  description: |
    # Features
    - Get reviews
    - Post review
  termsOfService: "https://shop-review.com/terms/"
  contact:
    name: "Customer Support"
    url: "https://shop-review.com/support/"
    email: "support-desk@shop-review.com"
  license:
    name: "MIT license"
    url: "https://opensource.org/license/mit/"
  version: "1.0.0"

paths: {}
