openapi: "3.0.3"

info:
  title: "Shop Review API"
  version: "1.0.0"

tags:
- name: "shops"
  description: "Shop review operation"

paths:
  "/shops/{shopId}/reviews":
    parameters:
    - name: "shopId"
      in: "path"
      required: true
      schema: { type: string, example: "1" }

    get:
      summary: "Get specified shop reviews"
      tags: ["shops"]
      responses:
        "200":
          description: "Succes operation"
    post:
      summary: "Create reviews"
      tags: ["shops"]
      responses:
        "201":
          description: "Succes operation"
